import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { BedDouble, CarFront, MapPin, ShieldCheck, Users } from 'lucide-react';
import { BookingSearchEn } from '@/components/booking-search-en';
import { SiteFooter } from '@/components/site-footer';
import { WhatsappFloat } from '@/components/whatsapp-float';
import { UnitsShowcase } from '@/components/units-showcase';
import { BrandLogo } from '@/components/brand-logo';

export const metadata: Metadata = { title: 'Tamra Hospitality | A warm stay in North Jeddah', description: 'A welcoming two-bedroom family apartment in Al Aseel, North Jeddah.' };

const features = [{icon:BedDouble,title:'Two bedrooms',text:'One double bed and two single beds'},{icon:Users,title:'Up to 5 guests',text:'Comfortable family-friendly spaces'},{icon:CarFront,title:'Private parking',text:'A dedicated shaded parking spot'},{icon:ShieldCheck,title:'Instant confirmation',text:'Flexible cancellation policy'}];

export default function EnglishHome() { return <main dir="ltr" className="min-h-screen bg-background text-foreground"><header className="border-b border-border bg-background/90"><div className="site-shell flex h-20 items-center justify-between"><Link href="/en" className="flex items-center gap-3"><BrandLogo/><span><strong className="block text-xl">Tamra</strong><small className="text-muted-foreground">HOSPITALITY</small></span></Link><Link href="/" className="rounded-full px-4 py-2 text-sm hover:bg-muted">العربية</Link></div></header><section className="site-shell py-6 sm:py-10"><div className="hero-card relative min-h-[650px] overflow-hidden rounded-[2rem]"><Image src="/images/living-window.jpeg" alt="Tamra apartment in North Jeddah" fill priority className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(30,19,15,.74),rgba(30,19,15,.12))]"/><div className="relative z-10 grid min-h-[650px] content-between gap-10 p-6 sm:p-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div className="max-w-2xl text-[#fffaf1]"><span className="rounded-full border border-white/25 bg-white/10 px-4 py-2 text-xs">Saudi hospitality with a warm spirit</span><h1 className="mt-6 text-5xl font-semibold leading-tight sm:text-7xl">Feel at home,<br/>stay from the heart.</h1><p className="mt-5 max-w-xl leading-8 text-white/75">A refined family apartment in Al Aseel, North Jeddah, with warm wooden details and everything you need for an effortless stay.</p></div><BookingSearchEn/></div></div></section><UnitsShowcase locale="en"/><section className="site-shell py-16"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="eyebrow">YOUR STAY</span><h2 className="mt-3 text-4xl font-semibold">Comfort in every detail</h2></div><span className="flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="size-4 text-accent"/>Al Aseel, North Jeddah</span></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(({icon:Icon,title,text})=><article key={title} className="feature-card"><span className="feature-icon"><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section><SiteFooter locale="en"/><WhatsappFloat locale="en"/></main>; }
