'use client';

import { useState } from 'react';
import Link from 'next/link';
import { CalendarDays, CheckCircle2, ChevronRight, LoaderCircle, Users, XCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { supabase } from '@/lib/supabase';

const UNIT_ID = '80c9be6e-4ea0-44be-883f-7ae53e117335';

export function BookingSearchEn() {
  const today = new Date().toISOString().slice(0, 10); const [checkIn, setCheckIn] = useState(''); const [checkOut, setCheckOut] = useState(''); const [guests, setGuests] = useState('2'); const [quote, setQuote] = useState<{available:boolean;nights:number;total_sar:number}|null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setQuote(null); if (!checkIn || !checkOut || checkOut <= checkIn) { setError('Choose a check-out date after check-in.'); return; } setLoading(true); const { data, error: requestError } = await supabase.rpc('check_unit_availability', { requested_unit_id: UNIT_ID, requested_check_in: checkIn, requested_check_out: checkOut, requested_guests: Number(guests) }); setLoading(false); if (requestError || !data?.[0]) { setError('Unable to check availability right now.'); return; } setQuote(data[0]); }
  return <form onSubmit={submit} className="booking-panel self-end rounded-[1.6rem] border border-white/45 bg-[#fffaf2]/95 p-5 shadow-2xl backdrop-blur-xl sm:p-6 lg:self-center"><div className="mb-5 flex items-start justify-between gap-4"><div><p className="text-xs text-accent-foreground">Book your stay</p><h2 className="mt-1 text-2xl font-semibold text-primary">Choose your dates</h2></div><div className="text-right"><strong className="text-2xl text-primary">SAR 400</strong><span className="block text-xs text-muted-foreground">per night</span></div></div><div className="grid gap-3 sm:grid-cols-2"><label className="booking-field"><span><CalendarDays />Check-in</span><Input required min={today} value={checkIn} onChange={(e)=>setCheckIn(e.target.value)} type="date" /></label><label className="booking-field"><span><CalendarDays />Check-out</span><Input required min={checkIn||today} value={checkOut} onChange={(e)=>setCheckOut(e.target.value)} type="date" /></label><label className="booking-field sm:col-span-2"><span><Users />Guests</span><select value={guests} onChange={(e)=>setGuests(e.target.value)} className="h-10 w-full bg-transparent text-sm outline-none">{[1,2,3,4,5].map((guest)=><option key={guest} value={guest}>{guest} guest{guest>1?'s':''}</option>)}</select></label></div><Button disabled={loading} type="submit" className="mt-4 h-13 w-full text-base">{loading?<><LoaderCircle className="animate-spin"/>Checking</>:<>Check availability <ChevronRight/></>}</Button>{error&&<p className="mt-3 flex items-center gap-2 rounded-xl bg-red-50 p-3 text-xs text-red-800"><XCircle className="size-4"/>{error}</p>}{quote&&<div className={`mt-3 rounded-xl p-3 text-sm ${quote.available?'bg-[#e4eadf] text-[#394034]':'bg-red-50 text-red-800'}`}>{quote.available?<div className="flex flex-wrap items-center justify-between gap-3"><span className="flex items-center gap-2"><CheckCircle2 className="size-4"/>Available for {quote.nights} nights — SAR {quote.total_sar}</span><Link className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground" href={`/book?checkIn=${checkIn}&checkOut=${checkOut}&guests=${guests}`}>Continue</Link></div>:'These dates are unavailable. Try another stay.'}</div>}</form>;
}
